spring:
  application:
    name: order
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.85.198:3306/springcloud_shell?characterEncoding=utf-8&useSSL=false
  jpa:
    showSql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port:9080